version: '3.8'

services:
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
  heimdall:
    container_name: heimdall
    volumes:
      - './heimdall:/config'
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - '8181:80'
      - '8443:443'
    image: linuxserver/heimdall

volumes:
  portainer_data:
